# Distributed Low Rank Recovery Problem

### 1. Original Eigengame -Sequential Algorithm Method

In [166]:
import numpy as np
from numpy import linalg as la
from numpy.random import RandomState

#generate random matrix X 
#X = np.ceil(np.random.normal(50, 10, size= (100, 100)))
Xo = RandomState(1234567890)
X = Xo.randint(50, size = (10, 10))

print(X)


[[ 2 38 47 12 33 43 41 14  9  4]
 [44 32 38 36 44 16 23 27 37  1]
 [15 44 46 19  1 43 39 17 44 10]
 [45 31 40 10 33 17 37  8 39 30]
 [43 27 27 25 40 42 34 28 27 49]
 [17 40  4 46 15 26 21 39 28 38]
 [19  3 44 25 40 37 33 41 19 15]
 [23 42  0 30 30 19 34 11 31  1]
 [49 43 17 13 48 48 34 31 33 38]
 [10 16  2 45  7 40 32 38 24 20]]


In [ ]:
'''
Changes: 
- array 100x100
- for v initial randomly generate a vector 
- take away for loop for i 
- rewards = matrix multiplication
- compute gradient manually**
- implement ui based on equation 6 and 7
- fix t for loop --> ceiling
- check multiplication

Check:
- does ti --> ui include vj? correct way to write u?
- is r correct
- change if statement?
- okay to append first vi in array r?
'''


# a = alpha = step size
a = 0.01
# p = max error tolerance
p = 0.000001
# vi = initial vector - as a randomly generated vector with same dimmension as matrix
v = RandomState(1234567890)
vi = v.randint(50, size = (1, 10))

Xvi = np.dot(vi, X)
# utility gradient (equation 7) 
ui = 2 * X.T * Xvi
minimum = min(((la.norm(ui))/2), p)
ti = int(np.ceil((5/4) * pow(minimum,-2)))
# array to store previous vectors
r = []


for t in range(1, ti):
    rewards = Xvi
    #print(rewards)
    #print()
    # no penalty for first iteration bc no vj (previous vectors) 
    penalties = 0
    
    if (t != 1):
        # to iterate through previous vectors, smaller than vi
        for i in range(1, len(r)):
            vj = r[i]
            Xvj = np.dot(vj, X)
            penalties += (((np.inner(Xvi, Xvj))/(np.inner(Xvj, Xvj))) * Xvj)
    diff = rewards - penalties
    grad_vi = np.dot(diff, (2 * X.T))
    #print(grad_vi)
    #print()
    #grad_R_vi = grad_vi - ((np.inner(grad_vi, vi))* vi)
    # inner euclidean product of vi gradient and vi
    product = np.inner(grad_vi, vi)
    grad_R_vi = grad_vi - (np.dot(product, vi))
    #print(grad_R_vi)
    #print()
    der_vi = vi + (a * grad_R_vi)
    #print(der_vi)
    #print()
    vi = der_vi / (la.norm(der_vi))
    r.append(vi)
    print(vi)
    print()
# return vi 


In [ ]:
# true eigenvectors (to compare with approx eigenvectors from above)

from numpy import linalg as la
print(la.eig(X))
print()


In [ ]:
# selecting Column Vector
#print(X[:,:1])
print()

# transpose fnc
print(X.T)
#print(np.transpose(X))
print()
print()

# matrix multiplication
v1 = np.random.normal(5,1.5, size= (1, 10))
print(np.dot(v1, X))
print()
print(np.matmul(v1, X))
print()
print(v1 @ X)
print()

print(np.inner(v1, X))
print()

In [ ]:
# eigenvalues, eigenvectors, norm fncs

# 1st array = eigenvalues in asceding order
# 2nd array = normalized eigenvectors corresponding to eigenvalue
from numpy import linalg as la
print(la.eig(X))
print()
print(la.norm(X))


# 
### 2. Deflation Method

### 3. Eigengame with Parallelism

### 4. Deflation with Parallelism