# Distributed Low Rank Recovery Problem

### 1. Original Eigengame -Sequential Algorithm Method

In [158]:
import numpy as np
from numpy import linalg as la
from numpy.random import RandomState

#generate random matrix X 
#X = np.ceil(np.random.normal(50, 10, size= (100, 100)))
Xo = RandomState(1234567890)
X = Xo.randint(50, size = (10, 10))

print(X)


[[ 2 38 47 12 33 43 41 14  9  4]
 [44 32 38 36 44 16 23 27 37  1]
 [15 44 46 19  1 43 39 17 44 10]
 [45 31 40 10 33 17 37  8 39 30]
 [43 27 27 25 40 42 34 28 27 49]
 [17 40  4 46 15 26 21 39 28 38]
 [19  3 44 25 40 37 33 41 19 15]
 [23 42  0 30 30 19 34 11 31  1]
 [49 43 17 13 48 48 34 31 33 38]
 [10 16  2 45  7 40 32 38 24 20]]


In [ ]:
'''
Changes: 
- array 100x100
- for v initial randomly generate a vector 
- take away for loop for i 
- rewards = matrix multiplication
- compute gradient manually**
- implement ui based on equation 6 and 7
- fix t for loop --> ceiling
- check multiplication

Check:
- does ti --> ui include vj? correct way to write u?
- is r correct
- change if statement?
- okay to append first vi in array r?
'''

# a = alpha = step size
a = 0.01
# p = max error tolerance
p = 0.000001
# vi = initial vector - as a randomly generated vector with same dimmension as matrix
v = RandomState(1234567890)
vi = v.randint(50, size = (1, 10))

Xvi = np.dot(vi, X)
# utility gradient (equation 7) 
ui = 2 * X.T * Xvi
minimum = min(((la.norm(ui))/2), p)
ti = int(np.ceil((5/4) * pow(minimum,-2)))
# array to store previous vectors
r = []


for t in range(1, ti):
    rewards = Xvi
    #print(rewards)
    #print()
    penalties = 0
# no penalty for first iteration bc no vj (previous vectors) 
    if (t != 1):
        # to iterate through previous vectors, smaller than vi
        for i in range(1, len(r)):
            vj = r[i]
            Xvj = np.dot(vj, X)
            penalties += (((np.inner(Xvi, Xvj))/(np.inner(Xvj, Xvj))) * Xvj)
    diff = rewards - penalties
    grad_vi = np.dot(diff, (2 * X.T))
    #print(grad_vi)
    #print()
    #grad_R_vi = grad_vi - ((np.inner(grad_vi, vi))* vi)
    # inner euclidean product of vi gradient and vi
    product = np.inner(grad_vi, vi)
    grad_R_vi = grad_vi - (np.dot(product, vi))
    #print(grad_R_vi)
    #print()
    der_vi = vi + (a * grad_R_vi)
    #print(der_vi)
    #print()
    vi = der_vi / (la.norm(der_vi))
    r.append(vi)
    print(vi)
    print()
# return vi 


[[-0.02139038 -0.40709951 -0.50353058 -0.12852829 -0.35352259 -0.46067607
  -0.43924636 -0.14996633 -0.09637563 -0.04282147]]

[[ 0.47442427 -0.01041773 -0.18173206  0.38625563  0.13898956 -0.15508646
  -0.10930506  0.23021471  0.56200729  0.41039569]]

[[ 0.03582192  0.43651747  0.46405554  0.10170858  0.09430971  0.46608021
   0.37638462  0.04348054 -0.10844021  0.4483713 ]]

[[-0.36790929 -0.02128329  0.01646463 -0.34073109 -0.43250115  0.04315649
  -0.05220403 -0.32389834 -0.66809001  0.07015433]]

[[-0.02927526 -0.44772874 -0.46547973 -0.11376161 -0.09624344 -0.46221101
  -0.37856527 -0.03468112  0.11004969 -0.43536382]]

[[-0.3700832  -0.01775224  0.01686653 -0.33685745 -0.43182516  0.04198624
  -0.05159381 -0.32678994 -0.66852961  0.06591375]]

[[-0.02713168 -0.45129609 -0.46587709 -0.11767764 -0.0969077  -0.46095125
  -0.37920053 -0.03180561  0.11049688 -0.43107409]]

[[-0.37137457 -0.01566897  0.01708743 -0.33454558 -0.43140877  0.04128218
  -0.05124834 -0.32851022 -0.66876309

[[-3.81688534e-01  5.34608468e-04  1.84239171e-02 -3.15863212e-01
  -4.27639247e-01  3.56235248e-02 -4.89633767e-02 -3.42316565e-01
  -6.69835534e-01  4.24561102e-02]]

[[-0.01553786 -0.46973173 -0.46744406 -0.13882491 -0.10107594 -0.45440156
  -0.38189934 -0.01624952  0.11184289 -0.40745216]]

[[-3.81726757e-01  5.93099984e-04  1.84275120e-02 -3.15793377e-01
  -4.27623732e-01  3.56027504e-02 -4.89565446e-02 -3.42367977e-01
  -6.69836785e-01  4.23768422e-02]]

[[-0.01549949 -0.46979059 -0.46744768 -0.13889516 -0.1010915  -0.45438054
  -0.38190627 -0.01619788  0.11184419 -0.40737245]]

[[-3.81764505e-01  6.50852113e-04  1.84310525e-02 -3.15724406e-01
  -4.27608398e-01  3.55822371e-02 -4.89498098e-02 -3.42418751e-01
  -6.69837999e-01  4.22985476e-02]]

[[-0.0154616  -0.4698487  -0.46745125 -0.13896453 -0.10110687 -0.45435979
  -0.38191309 -0.01614688  0.11184545 -0.40729371]]

[[-0.38180179  0.00070788  0.01843454 -0.31565628 -0.42759324  0.03556198
  -0.04894317 -0.3424689  -0.66983918 

[[-0.01388209 -0.47225991 -0.46759133 -0.14185903 -0.10175814 -0.45349806
  -0.38218635 -0.01401918  0.1118799  -0.40400119]]

[[-0.3833599   0.00308096  0.01857193 -0.31280582 -0.42694978  0.03471771
  -0.04867635 -0.34456668 -0.66987088  0.03897794]]

[[-0.01385979 -0.4722938  -0.46759318 -0.14189994 -0.10176748 -0.45348593
  -0.38219005 -0.01398911  0.11188013 -0.40395456]]

[[-0.38338194  0.0031144   0.01857375 -0.31276544 -0.42694054  0.0347058
  -0.04867272 -0.34459639 -0.66987108  0.03893189]]

[[-0.01383765 -0.47232744 -0.46759502 -0.14194055 -0.10177676 -0.4534739
  -0.38219372 -0.01395926  0.11188036 -0.40390826]]

[[-0.38340383  0.00314758  0.01857556 -0.31272536 -0.42693135  0.03469397
  -0.04866913 -0.34462588 -0.66987128  0.03888618]]

[[-0.01381567 -0.47236083 -0.46759685 -0.14198087 -0.10178597 -0.45346196
  -0.38219736 -0.01392963  0.11188057 -0.40386229]]

[[-0.38342556  0.00318052  0.01857736 -0.31268556 -0.42692223  0.03468224
  -0.04866556 -0.34465517 -0.66987146  

[[-0.01309791 -0.47344889 -0.46765462 -0.14329814 -0.10208903 -0.45307257
  -0.38231384 -0.0129615   0.11188373 -0.40235882]]

[[-0.38413568  0.00425501  0.01863425 -0.3113841  -0.42662205  0.03429915
  -0.04855132 -0.3456126  -0.66987378  0.03735505]]

[[-0.01308069 -0.47347493 -0.46765597 -0.14332975 -0.10209635 -0.45306325
  -0.38231658 -0.01293828  0.11188371 -0.40232271]]

[[-0.38415273  0.00428074  0.01863558 -0.31135285 -0.42661479  0.03428997
  -0.04854863 -0.34563559 -0.66987374  0.03731933]]

[[-0.01306358 -0.47350082 -0.4676573  -0.14336118 -0.10210363 -0.45305398
  -0.3823193  -0.01291518  0.11188369 -0.4022868 ]]

[[-0.38416967  0.00430633  0.01863689 -0.31132177 -0.42660758  0.03428084
  -0.04854596 -0.34565845 -0.66987371  0.03728382]]

[[-0.01304656 -0.47352656 -0.46765863 -0.14339243 -0.10211087 -0.45304476
  -0.382322   -0.01289221  0.11188367 -0.40225109]]

[[-0.38418652  0.00433177  0.0186382  -0.31129087 -0.4266004   0.03427176
  -0.04854331 -0.34568118 -0.66987366

[[-0.38469528  0.00509876  0.01867671 -0.31035755 -0.4263826   0.03399802
  -0.04846439 -0.34636768 -0.66987051  0.03618106]]

[[-0.01251865 -0.47432372 -0.46769873 -0.1443621  -0.10233667 -0.45275927
  -0.38240452 -0.01217961  0.11188088 -0.40114228]]

[[-0.38470942  0.00512005  0.01867776 -0.3103316  -0.42637651  0.03399042
  -0.04846222 -0.34638677 -0.66987037  0.03615135]]

[[-0.01250445 -0.47434514 -0.46769979 -0.1443882  -0.10234278 -0.4527516
  -0.38240671 -0.01216043  0.11188075 -0.4011124 ]]

[[-0.3847235   0.00514124  0.0186788  -0.31030576 -0.42637045  0.03398285
  -0.04846007 -0.34640577 -0.66987023  0.03612178]]

[[-0.01249031 -0.47436646 -0.46770083 -0.14441418 -0.10234886 -0.45274396
  -0.38240888 -0.01214134  0.11188061 -0.40108267]]

[[-0.38473751  0.00516233  0.01867983 -0.31028005 -0.42636442  0.03397532
  -0.04845794 -0.34642468 -0.66987008  0.03609235]]

[[-0.01247623 -0.47438767 -0.46770187 -0.14444004 -0.10235492 -0.45273636
  -0.38241104 -0.01212234  0.11188048 

[[-0.01192617 -0.47521553 -0.46774152 -0.14545118 -0.10259282 -0.4524397
  -0.3824942  -0.0113793   0.11187296 -0.39989494]]

[[-0.38529674  0.00600273  0.01872001 -0.30925323 -0.42612236  0.03367511
  -0.048374   -0.34717986 -0.66986198  0.03491606]]

[[-0.0119145  -0.47523305 -0.46774234 -0.14547263 -0.10259789 -0.45243341
  -0.38249593 -0.01136354  0.11187275 -0.39987036]]

[[-0.38530831  0.00602008  0.01872082 -0.30923198 -0.42611732  0.03366891
  -0.04837229 -0.34719549 -0.66986177  0.0348917 ]]

[[-0.01190288 -0.47525051 -0.46774316 -0.145494   -0.10260295 -0.45242716
  -0.38249766 -0.01134784  0.11187254 -0.39984586]]

[[-0.38531983  0.00603737  0.01872163 -0.30921082 -0.42611231  0.03366273
  -0.04837059 -0.34721105 -0.66986155  0.03486743]]

[[-0.01189131 -0.4752679  -0.46774397 -0.14551528 -0.10260798 -0.45242092
  -0.38249938 -0.0113322   0.11187233 -0.39982146]]

[[-0.38533131  0.00605459  0.01872243 -0.30918973 -0.42610731  0.03365658
  -0.0483689  -0.34722656 -0.66986134 

[[-0.01147165 -0.4758976  -0.46777276 -0.14628723 -0.10279128 -0.45219514
  -0.38256088 -0.01076496  0.11186345 -0.398936  ]]

[[-0.38574757  0.00667831  0.01875089 -0.30842484 -0.42592535  0.03343361
  -0.04830833 -0.34778906 -0.66985217  0.03396572]]

[[-0.01146163 -0.47591262 -0.46777343 -0.14630567 -0.10279567 -0.45218976
  -0.38256233 -0.01075141  0.1118632  -0.39891483]]

[[-0.38575752  0.00669319  0.01875155 -0.30840656 -0.42592098  0.03342828
  -0.04830691 -0.3478025  -0.66985192  0.03394474]]

[[-0.01145164 -0.47592759 -0.4677741  -0.14632405 -0.10280005 -0.45218439
  -0.38256378 -0.0107379   0.11186296 -0.39889374]]

[[-0.38576743  0.00670802  0.01875222 -0.30838834 -0.42591663  0.03342298
  -0.04830548 -0.3478159  -0.66985167  0.03392383]]

[[-0.01144169 -0.4759425  -0.46777477 -0.14634237 -0.10280442 -0.45217904
  -0.38256522 -0.01072444  0.11186271 -0.39887271]]

[[-0.3857773   0.0067228   0.01875288 -0.30837019 -0.42591229  0.0334177
  -0.04830407 -0.34782925 -0.66985142 

[[-0.01110376 -0.47644838 -0.46779704 -0.14696432 -0.10295316 -0.45199758
  -0.38261351 -0.01026742  0.11185356 -0.39815847]]

[[-0.38611264  0.00722412  0.0187749  -0.30775363 -0.42576458  0.03323838
  -0.04825647 -0.34828264 -0.66984207  0.03319481]]

[[-0.0110949  -0.47646163 -0.46779761 -0.14698064 -0.10295707 -0.45199283
  -0.38261477 -0.01025544  0.1118533  -0.39813972]]

[[-0.38612143  0.00723726  0.01877546 -0.30773745 -0.4257607   0.03323368
  -0.04825524 -0.34829453 -0.66984181  0.03317622]]

[[-0.01108607 -0.47647484 -0.46779818 -0.1469969  -0.10296097 -0.45198809
  -0.38261602 -0.01024349  0.11185303 -0.39812103]]

[[-0.3861302   0.00725035  0.01877603 -0.30772132 -0.42575682  0.033229
  -0.04825401 -0.34830639 -0.66984154  0.03315769]]

[[-0.01107726 -0.47648802 -0.46779875 -0.14701312 -0.10296487 -0.45198336
  -0.38261726 -0.01023157  0.11185277 -0.3981024 ]]

[[-0.38613894  0.00726341  0.01877659 -0.30770525 -0.42575296  0.03322433
  -0.04825278 -0.34831821 -0.66984127  

[[-0.01076839 -0.47694946 -0.46781838 -0.14758187 -0.10310171 -0.45181778
  -0.38266045 -0.00981366  0.11184284 -0.3974486 ]]

[[-0.38644554  0.00772087  0.01879602 -0.30714123 -0.42561702  0.03306063
  -0.04821021 -0.34873295 -0.66983118  0.03249074]]

[[-0.01076047 -0.47696128 -0.46781888 -0.14759645 -0.10310523 -0.45181354
  -0.38266154 -0.00980294  0.11184256 -0.39743183]]

[[-0.3864534   0.00773258  0.01879651 -0.30712677 -0.42561353  0.03305643
  -0.04820913 -0.34874359 -0.6698309   0.03247411]]

[[-0.01075257 -0.47697307 -0.46781937 -0.147611   -0.10310874 -0.45180931
  -0.38266263 -0.00979225  0.11184229 -0.3974151 ]]

[[-0.38646124  0.00774427  0.018797   -0.30711234 -0.42561004  0.03305225
  -0.04820805 -0.34875419 -0.66983063  0.03245751]]

[[-0.01074469 -0.47698483 -0.46781986 -0.14762551 -0.10311224 -0.45180509
  -0.38266372 -0.00978159  0.11184202 -0.39739842]]

[[-0.38646906  0.00775593  0.01879748 -0.30709795 -0.42560656  0.03304808
  -0.04820698 -0.34876477 -0.66983035

[[-0.38674476  0.00816656  0.01881437 -0.30659052 -0.42548361  0.03290107
  -0.04816946 -0.34913789 -0.66982002  0.03185703]]

[[-0.01045986 -0.47740958 -0.46783736 -0.14815023 -0.10323919 -0.45165263
  -0.38270273 -0.00939603  0.11183153 -0.39679467]]

[[-0.38675187  0.00817714  0.0188148  -0.30657744 -0.42548043  0.03289729
  -0.0481685  -0.34914751 -0.66981974  0.03184197]]

[[-0.01045272 -0.47742022 -0.46783779 -0.14816339 -0.10324238 -0.45164881
  -0.3827037  -0.00938636  0.11183125 -0.39677953]]

[[-0.38675896  0.00818769  0.01881523 -0.30656439 -0.42547726  0.03289351
  -0.04816755 -0.3491571  -0.66981946  0.03182694]]

[[-0.0104456  -0.47743083 -0.46783822 -0.14817651 -0.10324556 -0.451645
  -0.38270467 -0.00937672  0.11183097 -0.39676443]]

[[-0.38676603  0.00819821  0.01881565 -0.30655137 -0.4254741   0.03288974
  -0.0481666  -0.34916668 -0.66981917  0.03181196]]

[[-0.01043849 -0.47744142 -0.46783865 -0.1481896  -0.10324874 -0.4516412
  -0.38270563 -0.0093671   0.11183069 -0

[[-0.38699692  0.00854158  0.01882938 -0.30612623 -0.42537059  0.03276678
  -0.04813574 -0.34947928 -0.6698096   0.03132233]]

[[-0.01020652 -0.47778679 -0.46785247 -0.14861711 -0.10335267 -0.4515172
  -0.38273682 -0.00905297  0.11182121 -0.39625708]]

[[-0.38700345  0.00855128  0.01882976 -0.30611422 -0.42536766  0.03276331
  -0.04813487 -0.34948811 -0.66980932  0.03130849]]

[[-0.01019996 -0.47779654 -0.46785285 -0.14862919 -0.10335561 -0.45151369
  -0.3827377  -0.00904409  0.11182093 -0.39624316]]

[[-0.38700996  0.00856095  0.01883014 -0.30610223 -0.42536474  0.03275984
  -0.04813401 -0.34949693 -0.66980903  0.03129467]]

[[-0.01019342 -0.47780627 -0.46785324 -0.14864125 -0.10335855 -0.4515102
  -0.38273857 -0.00903523  0.11182065 -0.39622927]]

[[-0.38701646  0.00857061  0.01883052 -0.30609026 -0.42536182  0.03275638
  -0.04813315 -0.34950573 -0.66980875  0.03128089]]

[[-0.01018689 -0.47781598 -0.46785362 -0.14865328 -0.10336148 -0.45150671
  -0.38273944 -0.00902639  0.11182037 -

[[-0.00999749 -0.4780976  -0.46786461 -0.14900245 -0.1034467  -0.45140558
  -0.38276452 -0.00876982  0.11181199 -0.39581307]]

[[-0.38721106  0.00885962  0.01884179 -0.30573182 -0.42527421  0.03265286
  -0.04810755 -0.34976928 -0.66980002  0.0308678 ]]

[[-0.00999138 -0.47810668 -0.46786496 -0.14901371 -0.10344945 -0.45140232
  -0.38276532 -0.00876155  0.11181171 -0.39580008]]

[[-0.38721713  0.00886863  0.01884214 -0.30572064 -0.42527147  0.03264963
  -0.04810675 -0.3497775  -0.66979974  0.03085492]]

[[-0.00998528 -0.47811574 -0.46786531 -0.14902496 -0.1034522  -0.45139907
  -0.38276612 -0.00875329  0.11181143 -0.39578713]]

[[-0.38722319  0.00887762  0.01884248 -0.30570948 -0.42526874  0.03264641
  -0.04810596 -0.34978571 -0.66979946  0.03084206]]

[[-0.0099792  -0.47812478 -0.46786566 -0.14903617 -0.10345494 -0.45139582
  -0.38276692 -0.00874504  0.11181115 -0.3957742 ]]

[[-0.38722923  0.00888659  0.01884283 -0.30569835 -0.42526601  0.03264319
  -0.04810517 -0.34979389 -0.66979918

[[-0.38742767  0.00918095  0.01885403 -0.30533272 -0.42517632  0.03253773
  -0.04807945 -0.35006273 -0.66978966  0.03040759]]

[[-0.00977375 -0.47842987 -0.46787729 -0.14941503 -0.10354775 -0.45128623
  -0.38279373 -0.00846666  0.11180142 -0.39533738]]

[[-0.38743331  0.00918931  0.01885435 -0.30532233 -0.42517377  0.03253473
  -0.04807872 -0.35007037 -0.66978938  0.0303956 ]]

[[-0.00976809 -0.47843828 -0.46787761 -0.14942548 -0.10355031 -0.45128321
  -0.38279446 -0.00845898  0.11180114 -0.39532533]]

[[-0.38743894  0.00919765  0.01885466 -0.30531196 -0.42517122  0.03253174
  -0.04807799 -0.350078   -0.6697891   0.03038364]]

[[-0.00976243 -0.47844667 -0.46787792 -0.14943591 -0.10355287 -0.4512802
  -0.38279519 -0.00845132  0.11180086 -0.3953133 ]]

[[-0.38744455  0.00920598  0.01885497 -0.30530161 -0.42516868  0.03252876
  -0.04807727 -0.35008561 -0.66978882  0.0303717 ]]

[[-0.00975679 -0.47845504 -0.46787824 -0.14944632 -0.10355543 -0.45127719
  -0.38279592 -0.00844367  0.11180059 

[[-0.00957634 -0.47872268 -0.4678882  -0.14977917 -0.10363725 -0.45118104
  -0.38281913 -0.00819909  0.11179148 -0.39491728]]

[[-0.38762943  0.00947988  0.01886516 -0.30496087 -0.4250848   0.0324306
  -0.04805365 -0.35033615 -0.66977938  0.02997853]]

[[-0.00957104 -0.47873054 -0.46788849 -0.14978895 -0.10363966 -0.45117822
  -0.38281981 -0.0081919   0.11179121 -0.39490599]]

[[-0.3876347   0.00948768  0.01886545 -0.30495116 -0.4250824   0.0324278
  -0.04805298 -0.35034329 -0.66977911  0.02996733]]

[[-0.00956575 -0.47873838 -0.46788878 -0.14979871 -0.10364206 -0.4511754
  -0.38282048 -0.00818473  0.11179093 -0.39489473]]

[[-0.38763995  0.00949546  0.01886573 -0.30494147 -0.42508001  0.03242501
  -0.04805231 -0.35035041 -0.66977883  0.02995615]]

[[-0.00956047 -0.47874621 -0.46788907 -0.14980845 -0.10364446 -0.45117259
  -0.38282115 -0.00817757  0.11179066 -0.39488349]]

[[-0.3876452   0.00950323  0.01886602 -0.3049318  -0.42507763  0.03242223
  -0.04805165 -0.35035752 -0.66977856  0

[[-0.38780833  0.00974466  0.0188748  -0.30463105 -0.42500335  0.03233569
  -0.04803107 -0.35057866 -0.66976978  0.02959777]]

[[-0.0093913  -0.47899685 -0.4678982  -0.1501206  -0.10372145 -0.45108253
  -0.38284262 -0.0079482   0.11178165 -0.39452317]]

[[-0.38781328  0.00975199  0.01887506 -0.30462192 -0.42500109  0.03233306
  -0.04803045 -0.35058537 -0.6697695   0.02958722]]

[[-0.00938632 -0.47900423 -0.46789846 -0.15012979 -0.10372372 -0.45107988
  -0.38284325 -0.00794145  0.11178138 -0.39451256]]

[[-0.38781823  0.00975931  0.01887532 -0.3046128  -0.42499884  0.03233044
  -0.04802983 -0.35059208 -0.66976923  0.02957668]]

[[-0.00938135 -0.47901159 -0.46789873 -0.15013896 -0.10372598 -0.45107723
  -0.38284387 -0.00793471  0.11178111 -0.39450197]]

[[-0.38782317  0.00976661  0.01887559 -0.30460369 -0.42499659  0.03232782
  -0.04802922 -0.35059877 -0.66976896  0.02956617]]

[[-0.00937639 -0.47901893 -0.46789899 -0.15014811 -0.10372824 -0.45107459
  -0.3828445  -0.00792799  0.11178084

[[-0.38797695  0.00999399  0.01888369 -0.30432009 -0.42492634  0.0322463
  -0.04801006 -0.3508073  -0.66976029  0.02923859]]

[[-0.00922188 -0.47924763 -0.46790715 -0.15043329 -0.10379879 -0.45099241
  -0.38286386 -0.00771844  0.11177222 -0.39416205]]

[[-0.38798163  0.0100009   0.01888393 -0.30431146 -0.4249242   0.03224382
  -0.04800948 -0.35081364 -0.66976002  0.02922862]]

[[-0.00921717 -0.47925458 -0.46790739 -0.15044196 -0.10380093 -0.45098991
  -0.38286445 -0.00771206  0.11177195 -0.39415202]]

[[-0.3879863   0.01000781  0.01888418 -0.30430285 -0.42492207  0.03224134
  -0.0480089  -0.35081998 -0.66975975  0.02921866]]

[[-0.00921248 -0.47926152 -0.46790764 -0.15045063 -0.10380308 -0.45098741
  -0.38286503 -0.0077057   0.11177168 -0.39414202]]

[[-0.38799097  0.0100147   0.01888442 -0.30429425 -0.42491993  0.03223887
  -0.04800833 -0.3508263  -0.66975949  0.02920873]]

[[-0.0092078  -0.47926845 -0.46790788 -0.15045927 -0.10380522 -0.45098492
  -0.38286561 -0.00769934  0.11177141 

[[-0.00906166 -0.47948454 -0.46791544 -0.15072905 -0.10387214 -0.45090725
  -0.38288371 -0.0075011   0.1117629  -0.39382031]]

[[-0.38814085  0.01023609  0.01889215 -0.30401779 -0.42485127  0.03215949
  -0.04798988 -0.35102958 -0.66975067  0.02888924]]

[[-0.00905721 -0.47949112 -0.46791567 -0.15073727 -0.10387418 -0.45090489
  -0.38288426 -0.00749506  0.11176264 -0.39381081]]

[[-0.38814527  0.01024262  0.01889238 -0.30400962 -0.42484924  0.03215714
  -0.04798934 -0.35103558 -0.66975041  0.0288798 ]]

[[-0.00905276 -0.47949769 -0.46791589 -0.15074548 -0.10387622 -0.45090253
  -0.3828848  -0.00748903  0.11176238 -0.39380132]]

[[-0.38814969  0.01024914  0.0188926  -0.30400147 -0.42484721  0.0321548
  -0.0479888  -0.35104157 -0.66975014  0.02887038]]

[[-0.00904832 -0.47950425 -0.46791612 -0.15075367 -0.10387826 -0.45090017
  -0.38288535 -0.00748301  0.11176211 -0.39379185]]

[[-0.3881541   0.01025565  0.01889283 -0.30399334 -0.42484519  0.03215247
  -0.04798826 -0.35104756 -0.66974988 

[[-0.38828765  0.01045275  0.01889958 -0.30374694 -0.42478383  0.03208178
  -0.04797201 -0.35122873 -0.66974173  0.0285761 ]]

[[-0.00890971 -0.47970904 -0.46792314 -0.15100962 -0.10394191 -0.45082656
  -0.38290232 -0.00729493  0.11175372 -0.39349597]]

[[-0.38829186  0.01045896  0.01889979 -0.30373917 -0.42478189  0.03207956
  -0.0479715  -0.35123444 -0.66974146  0.02856712]]

[[-0.00890548 -0.47971528 -0.46792336 -0.15101743 -0.10394386 -0.45082431
  -0.38290284 -0.00728919  0.11175346 -0.39348695]]

[[-0.38829606  0.01046515  0.0189     -0.30373142 -0.42477996  0.03207733
  -0.04797099 -0.35124014 -0.6697412   0.02855815]]

[[-0.00890125 -0.47972152 -0.46792357 -0.15102523 -0.1039458  -0.45082207
  -0.38290335 -0.00728346  0.1117532  -0.39347793]]

[[-0.38830025  0.01047135  0.01890021 -0.30372368 -0.42477803  0.03207511
  -0.04797049 -0.35124583 -0.66974094  0.0285492 ]]

[[-0.00889704 -0.47972774 -0.46792378 -0.15103301 -0.10394774 -0.45081983
  -0.38290386 -0.00727774  0.11175294

[[-0.00876521 -0.47992232 -0.46793033 -0.15127647 -0.10400843 -0.45074988
  -0.38291983 -0.00709884  0.11174468 -0.39318737]]

[[-0.38843546  0.01067072  0.01890691 -0.30347416 -0.42471574  0.0320036
  -0.04795422 -0.3514293  -0.6697324   0.02826059]]

[[-0.00876119 -0.47992826 -0.46793053 -0.15128391 -0.10401029 -0.45074774
  -0.38292031 -0.00709338  0.11174443 -0.39317876]]

[[-0.38843946  0.01067661  0.01890711 -0.30346678 -0.42471389  0.03200149
  -0.04795374 -0.35143473 -0.66973214  0.02825205]]

[[-0.00875717 -0.4799342  -0.46793073 -0.15129133 -0.10401214 -0.45074561
  -0.38292079 -0.00708792  0.11174417 -0.39317017]]

[[-0.38844346  0.0106825   0.0189073  -0.3034594  -0.42471205  0.03199937
  -0.04795326 -0.35144015 -0.66973188  0.02824352]]

[[-0.00875315 -0.47994012 -0.46793092 -0.15129875 -0.104014   -0.45074348
  -0.38292128 -0.00708247  0.11174391 -0.3931616 ]]

[[-0.38844745  0.01068838  0.0189075  -0.30345204 -0.42471021  0.03199726
  -0.04795278 -0.35144556 -0.66973162 

[[-0.3885647   0.01086114  0.01891321 -0.30323562 -0.42465606  0.03193529
  -0.04793882 -0.35160469 -0.66972397  0.02798457]]

[[-0.00863134 -0.48011978 -0.46793686 -0.15152377 -0.10407023 -0.45067888
  -0.38293588 -0.00691711  0.11173603 -0.39290125]]

[[-0.38856852  0.01086678  0.01891339 -0.30322855 -0.42465429  0.03193327
  -0.04793836 -0.35160989 -0.66972372  0.02797639]]

[[-0.00862749 -0.48012546 -0.46793705 -0.15153088 -0.10407201 -0.45067684
  -0.38293634 -0.00691189  0.11173578 -0.39289303]]

[[-0.38857235  0.01087241  0.01891357 -0.3032215  -0.42465252  0.03193125
  -0.04793791 -0.35161508 -0.66972347  0.02796822]]

[[-0.00862365 -0.48013112 -0.46793724 -0.15153798 -0.10407378 -0.4506748
  -0.38293679 -0.00690667  0.11173553 -0.39288482]]

[[-0.38857617  0.01087803  0.01891376 -0.30321445 -0.42465076  0.03192923
  -0.04793746 -0.35162026 -0.66972322  0.02796007]]

[[-0.00861981 -0.48013678 -0.46793742 -0.15154506 -0.10407555 -0.45067277
  -0.38293725 -0.00690147  0.11173527 

[[-0.38869945  0.01105955  0.01891965 -0.30298683 -0.42459368  0.0318641
  -0.04792292 -0.35178763 -0.66971493  0.02769658]]

[[-0.00849593 -0.48031934 -0.46794335 -0.15177394 -0.10413288 -0.45060712
  -0.38295195 -0.00673327  0.11172701 -0.39261171]]

[[-0.38870311  0.01106493  0.01891982 -0.30298008 -0.42459199  0.03186217
  -0.04792249 -0.35179259 -0.66971468  0.02768877]]

[[-0.00849226 -0.48032475 -0.46794353 -0.15178073 -0.10413458 -0.45060517
  -0.38295238 -0.00672829  0.11172676 -0.39260385]]

[[-0.38870676  0.0110703   0.01892    -0.30297334 -0.42459029  0.03186024
  -0.04792206 -0.35179755 -0.66971443  0.02768096]]

[[-0.00848859 -0.48033016 -0.4679437  -0.15178751 -0.10413628 -0.45060323
  -0.38295281 -0.0067233   0.11172652 -0.392596  ]]

[[-0.38871041  0.01107567  0.01892017 -0.30296661 -0.4245886   0.03185832
  -0.04792163 -0.3518025  -0.66971418  0.02767316]]

[[-0.00848493 -0.48033556 -0.46794387 -0.15179428 -0.10413798 -0.45060129
  -0.38295325 -0.00671833  0.11172627 

[[-0.00837002 -0.48050477 -0.46794928 -0.15200662 -0.10419128 -0.45054043
  -0.38296674 -0.00656229  0.11171839 -0.3923423 ]]

[[-0.38882827  0.01124907  0.0189257  -0.30274896 -0.42453391  0.0317961
  -0.04790787 -0.35196253 -0.66970604  0.02742113]]

[[-0.0083665  -0.48050995 -0.46794944 -0.15201313 -0.10419291 -0.45053857
  -0.38296715 -0.00655751  0.11171814 -0.39233477]]

[[-0.38883177  0.01125421  0.01892586 -0.3027425  -0.42453228  0.03179425
  -0.04790747 -0.35196728 -0.66970579  0.02741365]]

[[-0.00836298 -0.48051513 -0.46794961 -0.15201962 -0.10419454 -0.45053671
  -0.38296756 -0.00655273  0.1117179  -0.39232724]]

[[-0.38883526  0.01125935  0.01892602 -0.30273605 -0.42453066  0.03179241
  -0.04790706 -0.35197203 -0.66970555  0.02740617]]

[[-0.00835947 -0.48052029 -0.46794977 -0.15202611 -0.10419617 -0.45053485
  -0.38296797 -0.00654796  0.11171765 -0.39231973]]

[[-0.38883875  0.01126448  0.01892619 -0.30272961 -0.42452904  0.03179056
  -0.04790666 -0.35197677 -0.6697053  

[[-0.00825267 -0.48067747 -0.46795471 -0.15222352 -0.10424582 -0.45047832
  -0.3829804  -0.00640289  0.11171013 -0.39209108]]

[[-0.38894493  0.01142057  0.01893108 -0.30253352 -0.42447966  0.03173455
  -0.04789438 -0.35212095 -0.66969777  0.02717155]]

[[-0.00824929 -0.48068244 -0.46795486 -0.15222977 -0.10424739 -0.45047653
  -0.38298079 -0.0063983   0.11170989 -0.39208384]]

[[-0.38894829  0.01142551  0.01893124 -0.30252731 -0.42447809  0.03173278
  -0.04789399 -0.35212552 -0.66969753  0.02716435]]

[[-0.00824591 -0.48068741 -0.46795502 -0.15223601 -0.10424897 -0.45047474
  -0.38298119 -0.00639371  0.11170965 -0.3920766 ]]

[[-0.38895164  0.01143044  0.01893139 -0.30252111 -0.42447653  0.03173101
  -0.04789361 -0.35213008 -0.66969729  0.02715717]]

[[-0.00824253 -0.48069237 -0.46795517 -0.15224225 -0.10425054 -0.45047296
  -0.38298158 -0.00638913  0.11170941 -0.39206938]]

[[-0.388955    0.01143537  0.01893154 -0.30251491 -0.42447497  0.03172924
  -0.04789322 -0.35213464 -0.66969705

[[-0.00813983 -0.48084341 -0.46795984 -0.1524321  -0.10429838 -0.45041863
  -0.38299342 -0.00624961  0.11170201 -0.3918494 ]]

[[-0.38905709  0.01158537  0.01893617 -0.30232632 -0.42442739  0.0316754
  -0.04788152 -0.35227331 -0.66968964  0.02693144]]

[[-0.00813658 -0.48084819 -0.46795999 -0.15243812 -0.10429989 -0.45041691
  -0.38299379 -0.00624519  0.11170177 -0.39184243]]

[[-0.38906033  0.01159012  0.01893632 -0.30232034 -0.42442588  0.0316737
  -0.04788115 -0.35227771 -0.6696894   0.02692451]]

[[-0.00813333 -0.48085297 -0.46796013 -0.15244412 -0.10430141 -0.45041519
  -0.38299417 -0.00624077  0.11170154 -0.39183547]]

[[-0.38906356  0.01159486  0.01893646 -0.30231437 -0.42442437  0.03167199
  -0.04788078 -0.3522821  -0.66968916  0.02691759]]

[[-0.00813008 -0.48085774 -0.46796028 -0.15245013 -0.10430292 -0.45041347
  -0.38299454 -0.00623636  0.1117013  -0.39182851]]

[[-0.38906679  0.0115996   0.01893661 -0.30230841 -0.42442287  0.03167029
  -0.04788041 -0.35228648 -0.66968892  

[[-0.00803118 -0.48100309 -0.4679647  -0.15263298 -0.10434908 -0.45036119
  -0.38300585 -0.00610198  0.11169401 -0.39161658]]

[[-0.38916511  0.01174396  0.018941   -0.30212676 -0.42437695  0.03161848
  -0.04786924 -0.35242005 -0.66968163  0.02670011]]

[[-0.00802805 -0.4810077  -0.46796484 -0.15263878 -0.10435055 -0.45035953
  -0.3830062  -0.00609772  0.11169378 -0.39160986]]

[[-0.38916822  0.01174854  0.01894114 -0.302121   -0.4243755   0.03161683
  -0.04786889 -0.35242429 -0.66968139  0.02669343]]

[[-0.00802491 -0.4810123  -0.46796498 -0.15264457 -0.10435201 -0.45035787
  -0.38300656 -0.00609347  0.11169354 -0.39160314]]

[[-0.38917134  0.01175311  0.01894127 -0.30211525 -0.42437404  0.03161519
  -0.04786854 -0.35242852 -0.66968116  0.02668676]]

[[-0.00802179 -0.4810169  -0.46796512 -0.15265035 -0.10435347 -0.45035622
  -0.38300691 -0.00608922  0.11169331 -0.39159644]]

[[-0.38917445  0.01175767  0.01894141 -0.3021095  -0.42437259  0.03161355
  -0.04786819 -0.35243274 -0.66968092

[[-0.38926926  0.01189679  0.01894558 -0.30193431 -0.42432823  0.03156361
  -0.04785751 -0.35256157 -0.66967374  0.02647695]]

[[-0.00792339 -0.48116141 -0.46796945 -0.1528323  -0.10439949 -0.45030423
  -0.38301807 -0.0059555   0.1116859  -0.39138549]]

[[-0.38927226  0.0119012   0.01894571 -0.30192875 -0.42432682  0.03156203
  -0.04785717 -0.35256566 -0.66967351  0.0264705 ]]

[[-0.00792037 -0.48116584 -0.46796958 -0.15283789 -0.1044009  -0.45030263
  -0.38301841 -0.0059514   0.11168567 -0.39137901]]

[[-0.38927527  0.01190561  0.01894584 -0.3019232  -0.42432541  0.03156045
  -0.04785683 -0.35256974 -0.66967328  0.02646406]]

[[-0.00791735 -0.48117028 -0.46796971 -0.15284347 -0.10440232 -0.45030104
  -0.38301875 -0.00594729  0.11168544 -0.39137253]]

[[-0.38927827  0.01191001  0.01894597 -0.30191765 -0.42432401  0.03155887
  -0.0478565  -0.35257382 -0.66967305  0.02645763]]

[[-0.00791434 -0.48117471 -0.46796985 -0.15284905 -0.10440373 -0.45029944
  -0.38301909 -0.0059432   0.11168521

[[-0.00781944 -0.481314   -0.46797396 -0.15302456 -0.10444819 -0.45024933
  -0.38302975 -0.00581421  0.11167792 -0.39116251]]

[[-0.38937562  0.01205277  0.01895018 -0.30173773 -0.42427837  0.03150761
  -0.04784562 -0.35270612 -0.66966552  0.02624894]]

[[-0.00781652 -0.48131828 -0.46797408 -0.15302996 -0.10444956 -0.45024779
  -0.38303008 -0.00581024  0.11167769 -0.39115625]]

[[-0.38937852  0.01205702  0.0189503  -0.30173237 -0.42427701  0.03150609
  -0.0478453  -0.35271006 -0.66966529  0.02624272]]

[[-0.00781361 -0.48132256 -0.46797421 -0.15303535 -0.10445093 -0.45024625
  -0.38303041 -0.00580628  0.11167747 -0.39115   ]]

[[-0.38938142  0.01206127  0.01895043 -0.30172702 -0.42427565  0.03150456
  -0.04784498 -0.352714   -0.66966506  0.02623651]]

[[-0.0078107  -0.48132683 -0.46797433 -0.15304073 -0.10445229 -0.45024471
  -0.38303073 -0.00580232  0.11167724 -0.39114375]]

[[-0.38938431  0.01206551  0.01895055 -0.30172167 -0.4242743   0.03150304
  -0.04784466 -0.35271793 -0.66966484

[[-0.38946981  0.01219083  0.01895419 -0.30156362 -0.42423414  0.03145805
  -0.04783518 -0.35283415 -0.6696581   0.02604692]]

[[-0.00772187 -0.48145714 -0.46797812 -0.15320504 -0.10449399 -0.45019782
  -0.38304063 -0.00568157  0.11167028 -0.39095314]]

[[-0.38947262  0.01219494  0.01895431 -0.30155843 -0.42423282  0.03145657
  -0.04783487 -0.35283797 -0.66965787  0.0260409 ]]

[[-0.00771905 -0.48146127 -0.46797824 -0.15321025 -0.10449531 -0.45019634
  -0.38304095 -0.00567774  0.11167006 -0.39094708]]

[[-0.38947543  0.01219905  0.01895443 -0.30155324 -0.4242315   0.03145509
  -0.04783456 -0.35284178 -0.66965765  0.02603488]]

[[-0.00771623 -0.48146541 -0.46797836 -0.15321547 -0.10449664 -0.45019485
  -0.38304126 -0.0056739   0.11166984 -0.39094103]]

[[-0.38947823  0.01220315  0.01895455 -0.30154806 -0.42423019  0.03145362
  -0.04783425 -0.35284559 -0.66965743  0.02602887]]

[[-0.00771342 -0.48146954 -0.46797848 -0.15322068 -0.10449796 -0.45019336
  -0.38304157 -0.00567008  0.11166961

[[-0.38956106  0.01232448  0.01895802 -0.30139494 -0.42419123  0.03141005
  -0.04782515 -0.35295819 -0.66965079  0.02585115]]

[[-0.00763019 -0.48159156 -0.46798198 -0.15337465 -0.10453709 -0.45014945
  -0.38305078 -0.00555692  0.11166298 -0.39075632]]

[[-0.38956378  0.01232846  0.01895813 -0.30138991 -0.42418995  0.03140862
  -0.04782485 -0.35296189 -0.66965057  0.02584531]]

[[-0.00762746 -0.48159557 -0.46798209 -0.1533797  -0.10453838 -0.45014801
  -0.38305108 -0.0055532   0.11166276 -0.39075045]]

[[-0.38956649  0.01233245  0.01895825 -0.30138489 -0.42418867  0.03140719
  -0.04782455 -0.35296559 -0.66965035  0.02583948]]

[[-0.00762472 -0.48159957 -0.46798221 -0.15338476 -0.10453966 -0.45014657
  -0.38305138 -0.00554949  0.11166254 -0.39074458]]

[[-0.38956921  0.01233642  0.01895836 -0.30137987 -0.42418739  0.03140577
  -0.04782425 -0.35296928 -0.66965013  0.02583365]]

[[-0.007622   -0.48160357 -0.46798232 -0.15338981 -0.10454095 -0.45014513
  -0.38305168 -0.00554578  0.11166232

[[-0.00754395 -0.48171794 -0.46798556 -0.15353421 -0.1045777  -0.45010398
  -0.38306025 -0.00543965  0.11165599 -0.39057111]]

[[-0.38964952  0.012454    0.01896168 -0.30123138 -0.42414955  0.03136354
  -0.04781549 -0.35307847 -0.66964358  0.02566127]]

[[-0.0075413  -0.48172182 -0.46798567 -0.15353912 -0.10457895 -0.45010258
  -0.38306054 -0.00543604  0.11165578 -0.39056541]]

[[-0.38965216  0.01245786  0.01896179 -0.3012265  -0.42414831  0.03136216
  -0.0478152  -0.35308206 -0.66964336  0.0256556 ]]

[[-0.00753865 -0.48172571 -0.46798577 -0.15354402 -0.1045802  -0.45010118
  -0.38306083 -0.00543243  0.11165556 -0.39055971]]

[[-0.38965479  0.01246172  0.0189619  -0.30122162 -0.42414706  0.03136077
  -0.04781492 -0.35308565 -0.66964314  0.02564994]]

[[-0.007536   -0.48172959 -0.46798588 -0.15354893 -0.10458145 -0.45009978
  -0.38306112 -0.00542883  0.11165534 -0.39055402]]

[[-0.38965743  0.01246558  0.01896201 -0.30121675 -0.42414582  0.03135939
  -0.04781463 -0.35308923 -0.66964293

[[-0.38974049  0.01258712  0.01896539 -0.30106315 -0.42410662  0.03131574
  -0.04780563 -0.35320218 -0.66963604  0.02546593]]

[[-0.00744989 -0.48185571 -0.4679894  -0.15370827 -0.10462207 -0.45005439
  -0.38307051 -0.00531172  0.11164825 -0.39036901]]

[[-0.38974305  0.01259086  0.0189655  -0.30105842 -0.42410541  0.03131439
  -0.04780536 -0.35320566 -0.66963583  0.02546043]]

[[-0.00744732 -0.48185947 -0.46798951 -0.15371303 -0.10462328 -0.45005304
  -0.38307079 -0.00530822  0.11164804 -0.39036349]]

[[-0.3897456   0.0125946   0.0189656  -0.3010537  -0.42410421  0.03131305
  -0.04780508 -0.35320914 -0.66963562  0.02545494]]

[[-0.00744475 -0.48186323 -0.46798961 -0.15371778 -0.10462449 -0.45005168
  -0.38307107 -0.00530473  0.11164782 -0.39035797]]

[[-0.38974816  0.01259834  0.0189657  -0.30104897 -0.424103    0.03131171
  -0.0478048  -0.35321261 -0.6696354   0.02544946]]

[[-0.00744218 -0.48186699 -0.46798971 -0.15372253 -0.10462571 -0.45005033
  -0.38307135 -0.00530124  0.11164761

[[-0.00736625 -0.48197816 -0.46799277 -0.15386307 -0.10466158 -0.45001032
  -0.38307956 -0.00519795  0.11164126 -0.39018924]]

[[-0.38982621  0.0127125   0.01896884 -0.30090461 -0.42406611  0.03127071
  -0.04779641 -0.35331877 -0.66962883  0.02528177]]

[[-0.00736375 -0.48198181 -0.46799287 -0.15386769 -0.10466276 -0.45000901
  -0.38307983 -0.00519455  0.11164105 -0.39018387]]

[[-0.3898287   0.01271613  0.01896894 -0.30090002 -0.42406493  0.0312694
  -0.04779614 -0.35332215 -0.66962862  0.02527644]]

[[-0.00736125 -0.48198546 -0.46799297 -0.15387231 -0.10466394 -0.45000769
  -0.3830801  -0.00519116  0.11164084 -0.3901785 ]]

[[-0.38983118  0.01271976  0.01896904 -0.30089543 -0.42406376  0.0312681
  -0.04779588 -0.35332552 -0.66962841  0.02527111]]

[[-0.00735876 -0.48198911 -0.46799307 -0.15387693 -0.10466512 -0.45000638
  -0.38308037 -0.00518776  0.11164063 -0.39017314]]

[[-0.38983366  0.01272338  0.01896914 -0.30089084 -0.42406259  0.0312668
  -0.04779561 -0.3533289  -0.6696282   0

[[-0.00728494 -0.48209713 -0.467996   -0.15401357 -0.10470005 -0.4499675
  -0.3830883  -0.00508733  0.11163436 -0.39001441]]

[[-0.38990706  0.01283069  0.01897205 -0.30075506 -0.42402784  0.03122826
  -0.04778778 -0.35342875 -0.66962193  0.02510803]]

[[-0.00728251 -0.48210068 -0.4679961  -0.15401807 -0.1047012  -0.44996622
  -0.38308856 -0.00508403  0.11163415 -0.39000919]]

[[-0.38990948  0.01283422  0.01897214 -0.3007506  -0.4240267   0.03122699
  -0.04778752 -0.35343203 -0.66962173  0.02510284]]

[[-0.00728008 -0.48210423 -0.4679962  -0.15402256 -0.10470235 -0.44996494
  -0.38308882 -0.00508073  0.11163394 -0.39000397]]

[[-0.38991189  0.01283775  0.01897224 -0.30074613 -0.42402555  0.03122572
  -0.04778726 -0.35343531 -0.66962152  0.02509765]]

[[-0.00727766 -0.48210778 -0.46799629 -0.15402705 -0.1047035  -0.44996367
  -0.38308908 -0.00507743  0.11163373 -0.38999875]]

[[-0.3899143   0.01284127  0.01897233 -0.30074167 -0.42402441  0.03122445
  -0.04778701 -0.35343859 -0.66962131 

[[-0.38998572  0.01294562  0.01897513 -0.30060955 -0.42399056  0.03118697
  -0.04777943 -0.35353575 -0.66961513  0.02493894]]

[[-0.00720347 -0.48221627 -0.4679992  -0.15416438 -0.10473865 -0.44992461
  -0.383097   -0.00497649  0.11162735 -0.38983918]]

[[-0.38998807  0.01294905  0.01897522 -0.30060521 -0.42398944  0.03118574
  -0.04777918 -0.35353895 -0.66961492  0.02493388]]

[[-0.00720111 -0.48221973 -0.46799929 -0.15416875 -0.10473977 -0.44992337
  -0.38309725 -0.00497328  0.11162714 -0.3898341 ]]

[[-0.38999042  0.01295249  0.01897531 -0.30060086 -0.42398833  0.03118451
  -0.04777894 -0.35354215 -0.66961472  0.02492883]]

[[-0.00719875 -0.48222318 -0.46799938 -0.15417312 -0.10474089 -0.44992213
  -0.3830975  -0.00497006  0.11162694 -0.38982902]]

[[-0.38999276  0.01295591  0.0189754  -0.30059652 -0.42398721  0.03118327
  -0.04777869 -0.35354534 -0.66961451  0.02492379]]

[[-0.00719639 -0.48222662 -0.46799948 -0.15417749 -0.10474201 -0.44992089
  -0.38309775 -0.00496686  0.11162673

[[-0.00712883 -0.4823254  -0.46800209 -0.15430258 -0.10477407 -0.44988533
  -0.38310491 -0.00487491  0.11162084 -0.38967856]]

[[-0.39006229  0.01305747  0.01897809 -0.30046787 -0.42395421  0.0311468
  -0.04777136 -0.35363995 -0.66960841  0.02477425]]

[[-0.00712652 -0.48232876 -0.46800218 -0.15430684 -0.10477516 -0.44988412
  -0.38310515 -0.00487178  0.11162063 -0.38967361]]

[[-0.39006458  0.01306081  0.01897817 -0.30046364 -0.42395312  0.03114559
  -0.04777112 -0.35364306 -0.66960821  0.02476933]]

[[-0.00712422 -0.48233212 -0.46800227 -0.1543111  -0.10477625 -0.44988291
  -0.3831054  -0.00486865  0.11162043 -0.38966866]]

[[-0.39006687  0.01306415  0.01897826 -0.30045941 -0.42395203  0.03114439
  -0.04777088 -0.35364617 -0.66960801  0.02476441]]

[[-0.00712193 -0.48233548 -0.46800235 -0.15431536 -0.10477734 -0.4498817
  -0.38310564 -0.00486552  0.11162023 -0.38966371]]

[[-0.39006916  0.01306749  0.01897835 -0.30045518 -0.42395095  0.0311432
  -0.04777064 -0.35364929 -0.66960781  0

[[-0.0070538  -0.48243503 -0.46800496 -0.1544415  -0.10480971 -0.44984587
  -0.38311281 -0.0047728   0.11161421 -0.38951708]]

[[-0.3901369   0.01316638  0.01898093 -0.30032983 -0.42391875  0.03110767
  -0.04776355 -0.35374147 -0.66960179  0.02461376]]

[[-0.00705156 -0.4824383  -0.46800504 -0.15444566 -0.10481078 -0.44984469
  -0.38311305 -0.00476975  0.11161401 -0.38951225]]

[[-0.39013913  0.01316964  0.01898102 -0.3003257  -0.42391769  0.0311065
  -0.04776332 -0.35374451 -0.66960159  0.02460896]]

[[-0.00704931 -0.48244158 -0.46800513 -0.15444981 -0.10481185 -0.44984351
  -0.38311328 -0.0047667   0.11161381 -0.38950742]]

[[-0.39014136  0.01317289  0.0189811  -0.30032157 -0.42391662  0.03110533
  -0.04776309 -0.35374754 -0.66960139  0.02460416]]

[[-0.00704707 -0.48244485 -0.46800521 -0.15445396 -0.10481291 -0.44984233
  -0.38311352 -0.00476365  0.11161361 -0.3895026 ]]

[[-0.39014359  0.01317614  0.01898118 -0.30031745 -0.42391557  0.03110416
  -0.04776286 -0.35375057 -0.66960119 

[[-0.39020963  0.01327252  0.01898367 -0.30019523 -0.42388413  0.03106954
  -0.04775599 -0.35384046 -0.66959525  0.02445724]]

[[-0.00697847 -0.48254505 -0.4680078  -0.154581   -0.10484555 -0.44980626
  -0.3831207  -0.00467027  0.11160747 -0.38935488]]

[[-0.39021181  0.01327569  0.01898375 -0.3001912  -0.42388309  0.0310684
  -0.04775576 -0.35384342 -0.66959505  0.02445255]]

[[-0.00697629 -0.48254824 -0.46800788 -0.15458505 -0.10484659 -0.44980511
  -0.38312093 -0.0046673   0.11160728 -0.38935018]]

[[-0.39021398  0.01327886  0.01898383 -0.30018718 -0.42388206  0.03106726
  -0.04775554 -0.35384638 -0.66959486  0.02444788]]

[[-0.0069741  -0.48255143 -0.46800796 -0.15458909 -0.10484763 -0.44980396
  -0.38312115 -0.00466432  0.11160708 -0.38934547]]

[[-0.39021615  0.01328203  0.01898391 -0.30018316 -0.42388102  0.03106612
  -0.04775531 -0.35384934 -0.66959466  0.0244432 ]]

[[-0.00697192 -0.48255462 -0.46800804 -0.15459314 -0.10484867 -0.44980281
  -0.38312138 -0.00466135  0.11160688 

In [155]:
# true eigenvectors (to compare with approx eigenvectors from above)

from numpy import linalg as la
print(la.eig(X))
print()


(array([283.36779219 +0.j        ,  35.79672573 +0.j        ,
        -4.31914761+41.37611659j,  -4.31914761-41.37611659j,
         6.66846178+20.73720723j,   6.66846178-20.73720723j,
       -38.16903563 +0.j        ,  -6.28104106+11.93744717j,
        -6.28104106-11.93744717j, -20.1320285  +0.j        ]), array([[ 0.27487859+0.j        , -0.31835309+0.j        ,
         0.02224085-0.06399155j,  0.02224085+0.06399155j,
        -0.31617368+0.10448458j, -0.31617368-0.10448458j,
        -0.5216358 +0.j        ,  0.43423817-0.19687809j,
         0.43423817+0.19687809j,  0.22904293+0.j        ],
       [ 0.34040118+0.j        , -0.46666794+0.j        ,
        -0.08651583+0.41111595j, -0.08651583-0.41111595j,
        -0.27049879+0.13428873j, -0.27049879-0.13428873j,
         0.38196427+0.j        ,  0.21907683+0.02786987j,
         0.21907683-0.02786987j,  0.27847466+0.j        ],
       [ 0.31378265+0.j        , -0.48389634+0.j        ,
         0.04296298-0.13329933j,  0.04296298+0.13329

In [161]:
# selecting Column Vector
#print(X[:,:1])
print()

# transpose fnc
print(X.T)
#print(np.transpose(X))
print()
print()

# matrix multiplication
v1 = np.random.normal(5,1.5, size= (1, 10))
print(np.dot(v1, X))
print()
print(np.matmul(v1, X))
print()
print(v1 @ X)
print()

print(np.inner(v1, X))
print()


[[ 2 44 15 45 43 17 19 23 49 10]
 [38 32 44 31 27 40  3 42 43 16]
 [47 38 46 40 27  4 44  0 17  2]
 [12 36 19 10 25 46 25 30 13 45]
 [33 44  1 33 40 15 40 30 48  7]
 [43 16 43 17 42 26 37 19 48 40]
 [41 23 39 37 34 21 33 34 34 32]
 [14 27 17  8 28 39 41 11 31 38]
 [ 9 37 44 39 27 28 19 31 33 24]
 [ 4  1 10 30 49 38 15  1 38 20]]


[[1420.79626056 1818.2481429  1479.70654127 1494.74069489 1525.27359868
  1859.37314719 1836.75867725 1414.57502952 1642.79684212 1176.32082411]]

[[1420.79626056 1818.2481429  1479.70654127 1494.74069489 1525.27359868
  1859.37314719 1836.75867725 1414.57502952 1642.79684212 1176.32082411]]

[[1420.79626056 1818.2481429  1479.70654127 1494.74069489 1525.27359868
  1859.37314719 1836.75867725 1414.57502952 1642.79684212 1176.32082411]]

[[1452.27598921 1674.64760992 1564.79424416 1610.55411393 1940.19480905
  1465.55169759 1641.23240269 1168.80589939 1993.37317632 1291.47075737]]



In [75]:
# eigenvalues, eigenvectors, norm fncs

# 1st array = eigenvalues in asceding order
# 2nd array = normalized eigenvectors corresponding to eigenvalue
from numpy import linalg as la
print(la.eig(X))
print()
print(la.norm(X))


(array([ 5.05700300e+03 +0.j        , -7.55596332e+01+78.92195506j,
       -7.55596332e+01-78.92195506j,  9.72631616e+01+45.88863327j,
        9.72631616e+01-45.88863327j, -3.07272075e+01+92.7453888j ,
       -3.07272075e+01-92.7453888j , -1.28237390e+00+95.88986704j,
       -1.28237390e+00-95.88986704j,  7.96321580e+01+53.21038417j,
        7.96321580e+01-53.21038417j,  1.84561237e+01+91.51333679j,
        1.84561237e+01-91.51333679j,  9.15573499e+01 +9.93343771j,
        9.15573499e+01 -9.93343771j, -9.38530775e+01 +6.16764913j,
       -9.38530775e+01 -6.16764913j,  6.84042720e+01+60.28344932j,
        6.84042720e+01-60.28344932j, -8.11135272e+01+37.00605669j,
       -8.11135272e+01-37.00605669j, -5.27928769e+01+71.40138549j,
       -5.27928769e+01-71.40138549j,  2.52209351e+01+82.77426879j,
        2.52209351e+01-82.77426879j,  5.06881431e+01+70.70982816j,
        5.06881431e+01-70.70982816j, -8.27241607e+01 +0.j        ,
        7.89900357e+01 +0.j        , -6.31856193e+01+50.17002

# 
### 2. Deflation Method

### 3. Eigengame with Parallelism

### 4. Deflation with Parallelism