# Distributed Low Rank Recovery Problem

### 1. Original Eigengame -Sequential Algorithm Method

In [158]:
import numpy as np
from numpy import linalg as la
from numpy.random import RandomState

#generate random matrix X 
#X = np.ceil(np.random.normal(50, 10, size= (100, 100)))
Xo = RandomState(1234567890)
X = Xo.randint(50, size = (10, 10))

print(X)


[[ 2 38 47 12 33 43 41 14  9  4]
 [44 32 38 36 44 16 23 27 37  1]
 [15 44 46 19  1 43 39 17 44 10]
 [45 31 40 10 33 17 37  8 39 30]
 [43 27 27 25 40 42 34 28 27 49]
 [17 40  4 46 15 26 21 39 28 38]
 [19  3 44 25 40 37 33 41 19 15]
 [23 42  0 30 30 19 34 11 31  1]
 [49 43 17 13 48 48 34 31 33 38]
 [10 16  2 45  7 40 32 38 24 20]]


In [ ]:
'''
Changes: 
- array 100x100
- for v initial randomly generate a vector 
- take away for loop for i 
- rewards = matrix multiplication
- compute gradient manually**
- implement ui based on equation 6 and 7
- fix t for loop --> ceiling
- check multiplication

Check:
- does ti --> ui include vj? correct way to write u?
- is r correct
- change if statement?
- okay to append first vi in array r?
'''

# a = alpha = step size
a = 0.01
# p = max error tolerance
p = 0.000001
# vi = initial vector - as a randomly generated vector with same dimmension as matrix
v = RandomState(1234567890)
vi = v.randint(50, size = (1, 10))

Xvi = np.dot(vi, X)
# utility gradient (equation 7) 
ui = 2 * X.T * Xvi
minimum = min(((la.norm(ui))/2), p)
ti = int(np.ceil((5/4) * pow(minimum,-2)))
# array to store previous vectors
r = []


for t in range(1, ti):
    rewards = Xvi
    #print(rewards)
    #print()
    penalties = 0
# no penalty for first iteration bc no vj (previous vectors) 
    if (t != 1):
        # print ('m')
        # to iterate through previous vectors, smaller than vi
        for i in range(1, len(r)):
            vj = r[i]
            Xvj = np.dot(vj, X)
            penalties += (((np.inner(Xvi, Xvj))/(np.inner(Xvj, Xvj))) * Xvj)
    diff = rewards - penalties
    grad_vi = np.dot(diff, (2 * X.T))
    #print(grad_vi)
    #print()
    #grad_R_vi = grad_vi - ((np.inner(grad_vi, vi))* vi)
    # inner euclidean product of vi gradient and vi
    product = np.inner(grad_vi, vi)
    grad_R_vi = grad_vi - (np.dot(product, vi))
    #print(grad_R_vi)
    #print()
    der_vi = vi + (np.dot(a, grad_R_vi))
    #print(der_vi)
    #print()
    vi = der_vi / (la.norm(der_vi))
    r.append(vi)
    print(vi)
    print()
# return vi 


[[-0.02139038 -0.40709951 -0.50353058 -0.12852829 -0.35352259 -0.46067607
  -0.43924636 -0.14996633 -0.09637563 -0.04282147]]

[[ 0.47442427 -0.01041773 -0.18173206  0.38625563  0.13898956 -0.15508646
  -0.10930506  0.23021471  0.56200729  0.41039569]]

[[ 0.03582192  0.43651747  0.46405554  0.10170858  0.09430971  0.46608021
   0.37638462  0.04348054 -0.10844021  0.4483713 ]]

[[-0.36790929 -0.02128329  0.01646463 -0.34073109 -0.43250115  0.04315649
  -0.05220403 -0.32389834 -0.66809001  0.07015433]]

[[-0.02927526 -0.44772874 -0.46547973 -0.11376161 -0.09624344 -0.46221101
  -0.37856527 -0.03468112  0.11004969 -0.43536382]]

[[-0.3700832  -0.01775224  0.01686653 -0.33685745 -0.43182516  0.04198624
  -0.05159381 -0.32678994 -0.66852961  0.06591375]]

[[-0.02713168 -0.45129609 -0.46587709 -0.11767764 -0.0969077  -0.46095125
  -0.37920053 -0.03180561  0.11049688 -0.43107409]]

[[-0.37137457 -0.01566897  0.01708743 -0.33454558 -0.43140877  0.04128218
  -0.05124834 -0.32851022 -0.66876309

[[-3.81048674e-01 -4.46328013e-04  1.83622747e-02 -3.17031660e-01
  -4.27897236e-01  3.59716751e-02 -4.90795975e-02 -3.41456238e-01
  -6.69811538e-01  4.37811562e-02]]

[[-0.01618008 -0.46874457 -0.46738194 -0.1376496  -0.10081731 -0.45475389
  -0.38178151 -0.01711365  0.11181799 -0.40878472]]

[[-3.81095784e-01 -3.73991327e-04  1.83669075e-02 -3.16945670e-01
  -4.27878354e-01  3.59460179e-02 -4.90709218e-02 -3.41519560e-01
  -6.69813502e-01  4.36837214e-02]]

[[-0.0161328  -0.46881737 -0.46738661 -0.1377361  -0.10083624 -0.45472792
  -0.38179031 -0.01705005  0.11182002 -0.40868673]]

[[-3.81142176e-01 -3.02774940e-04  1.83714549e-02 -3.16860986e-01
  -4.27859742e-01  3.59207555e-02 -4.90623967e-02 -3.41581921e-01
  -6.69815405e-01  4.35877527e-02]]

[[-0.01608624 -0.46888904 -0.46739119 -0.13782128 -0.1008549  -0.45470235
  -0.38179896 -0.01698742  0.11182199 -0.40859022]]

[[-3.81187872e-01 -2.32645188e-04  1.83759199e-02 -3.16777567e-01
  -4.27841392e-01  3.58958761e-02 -4.90540175e

[[-0.0144735  -0.47135967 -0.46754085 -0.14077463 -0.10151192 -0.45381997
  -0.38208661 -0.01481624  0.11187119 -0.4052364 ]]

[[-0.3827757   0.00219355  0.01852233 -0.31387536 -0.42719334  0.03503371
  -0.04877394 -0.3437797  -0.66986304  0.0401965 ]]

[[-0.01444641 -0.47140097 -0.46754322 -0.14082428 -0.10152313 -0.4538052
  -0.38209125 -0.01477974  0.11187169 -0.40517988]]

[[-0.38280244  0.00223423  0.01852465 -0.31382642 -0.42718226  0.03501923
  -0.04876941 -0.34381571 -0.6698635   0.04014078]]

[[-0.01441956 -0.4714419  -0.46754555 -0.1408735  -0.10153426 -0.45379057
  -0.38209584 -0.01474357  0.11187219 -0.40512386]]

[[-0.38282894  0.00227455  0.01852694 -0.31377792 -0.42717126  0.03500488
  -0.04876492 -0.3438514  -0.66986395  0.04008556]]

[[-0.01439294 -0.47148247 -0.46754787 -0.14092228 -0.10154529 -0.45377607
  -0.38210038 -0.01470771  0.11187267 -0.40506833]]

[[-0.38285522  0.00231451  0.01852921 -0.31372983 -0.42716035  0.03499066
  -0.04876048 -0.34388679 -0.66986439 

[[-0.38365475  0.00352777  0.01859609 -0.31226567 -0.4268258   0.03455848
  -0.04862821 -0.34496408 -0.66987299  0.03836177]]

[[-0.01356369 -0.47274331 -0.46761753 -0.14244318 -0.10189188 -0.45332511
  -0.38223877 -0.01358985  0.11188252 -0.40333498]]

[[-0.38367474  0.00355804  0.01859771 -0.31222903 -0.42681737  0.03454769
  -0.04862498 -0.34499104 -0.66987309  0.03831995]]

[[-0.01354362 -0.47277377 -0.46761916 -0.14248002 -0.10190035 -0.45331421
  -0.38224205 -0.01356277  0.11188264 -0.40329294]]

[[-0.3836946   0.00358811  0.01859931 -0.31219263 -0.42680899  0.03453697
  -0.04862176 -0.34501781 -0.66987319  0.03827841]]

[[-0.01352367 -0.47280402 -0.46762077 -0.14251663 -0.10190875 -0.45330339
  -0.3822453  -0.01353587  0.11188275 -0.40325117]]

[[-0.38371434  0.00361798  0.0186009  -0.31215647 -0.42680066  0.03452632
  -0.04861858 -0.34504442 -0.66987327  0.03823714]]

[[-0.01350385 -0.47283407 -0.46762237 -0.14255299 -0.10191711 -0.45329264
  -0.38224852 -0.01350914  0.11188285

[[-0.01283363 -0.47384838 -0.46767503 -0.14378346 -0.10220167 -0.45292953
  -0.38235558 -0.01260485  0.11188303 -0.40180415]]

[[-0.38439738  0.00464991  0.01865437 -0.31090414 -0.42651039  0.03415824
  -0.04851032 -0.34596564 -0.66987281  0.03680638]]

[[-0.01281786 -0.4738722  -0.46767623 -0.14381242 -0.10220841 -0.452921
  -0.38235805 -0.01258356  0.11188295 -0.40177103]]

[[-0.384413    0.00467347  0.01865556 -0.31087549 -0.42650371  0.03414984
  -0.0485079  -0.34598672 -0.66987272  0.03677361]]

[[-0.01280217 -0.47389589 -0.46767742 -0.14384124 -0.10221512 -0.45291251
  -0.38236051 -0.01256238  0.11188288 -0.40173808]]

[[-0.38442854  0.0046969   0.01865673 -0.31084698 -0.42649705  0.03414147
  -0.04850548 -0.34600769 -0.66987263  0.03674101]]

[[-0.01278656 -0.47391946 -0.46767861 -0.14386991 -0.10222179 -0.45290407
  -0.38236295 -0.01254131  0.1118828  -0.4017053 ]]

[[-0.384444    0.0047202   0.0186579  -0.31081862 -0.42649044  0.03413316
  -0.04850308 -0.34602855 -0.66987253  

[[-0.38486074  0.00534774  0.01868886 -0.31005386 -0.4263113   0.03390911
  -0.0484392  -0.34659104 -0.66986868  0.03583339]]

[[-0.01235246 -0.47457418 -0.46771097 -0.1446675  -0.10240823 -0.45266954
  -0.38242999 -0.01195518  0.11187917 -0.40079271]]

[[-0.38487412  0.00536787  0.01868984 -0.31002929 -0.42630553  0.03390192
  -0.04843718 -0.34660911 -0.66986852  0.03580526]]

[[-0.01233902 -0.47459443 -0.46771195 -0.14469221 -0.10241403 -0.45266229
  -0.38243204 -0.01193703  0.11187901 -0.40076442]]

[[-0.38488744  0.0053879   0.01869081 -0.31000483 -0.42629977  0.03389476
  -0.04843516 -0.3466271  -0.66986835  0.03577725]]

[[-0.01232563 -0.47461459 -0.46771293 -0.1447168  -0.1024198  -0.45265506
  -0.38243408 -0.01191895  0.11187885 -0.40073626]]

[[-0.38490071  0.00540785  0.01869177 -0.30998048 -0.42629405  0.03388764
  -0.04843316 -0.34664501 -0.66986818  0.03574937]]

[[-0.01231231 -0.47463465 -0.4677139  -0.14474129 -0.10242555 -0.45264788
  -0.38243611 -0.01190096  0.11187869

[[-0.0119145  -0.47523305 -0.46774234 -0.14547263 -0.10259789 -0.45243341
  -0.38249593 -0.01136354  0.11187275 -0.39987036]]

[[-0.38530831  0.00602008  0.01872082 -0.30923198 -0.42611732  0.03366891
  -0.04837229 -0.34719549 -0.66986177  0.0348917 ]]

[[-0.01190288 -0.47525051 -0.46774316 -0.145494   -0.10260295 -0.45242716
  -0.38249766 -0.01134784  0.11187254 -0.39984586]]

[[-0.38531983  0.00603737  0.01872163 -0.30921082 -0.42611231  0.03366273
  -0.04837059 -0.34721105 -0.66986155  0.03486743]]

[[-0.01189131 -0.4752679  -0.46774397 -0.14551528 -0.10260798 -0.45242092
  -0.38249938 -0.0113322   0.11187233 -0.39982146]]

[[-0.38533131  0.00605459  0.01872243 -0.30918973 -0.42610731  0.03365658
  -0.0483689  -0.34722656 -0.66986134  0.03484326]]

[[-0.01187978 -0.47528522 -0.46774477 -0.14553649 -0.102613   -0.45241471
  -0.38250109 -0.01131662  0.11187212 -0.39979716]]

[[-0.38534274  0.00607174  0.01872323 -0.30916873 -0.42610233  0.03365045
  -0.04836722 -0.347242   -0.66986112

[[-0.01148171 -0.47588253 -0.46777208 -0.14626873 -0.10278687 -0.45220055
  -0.38255943 -0.01077855  0.11186369 -0.39895723]]

[[-0.3857376   0.00666338  0.01875022 -0.30844318 -0.42592972  0.03343895
  -0.04830977 -0.34777557 -0.66985242  0.03398677]]

[[-0.01147165 -0.4758976  -0.46777276 -0.14628723 -0.10279128 -0.45219514
  -0.38256088 -0.01076496  0.11186345 -0.398936  ]]

[[-0.38574757  0.00667831  0.01875089 -0.30842484 -0.42592535  0.03343361
  -0.04830833 -0.34778906 -0.66985217  0.03396572]]

[[-0.01146163 -0.47591262 -0.46777343 -0.14630567 -0.10279567 -0.45218976
  -0.38256233 -0.01075141  0.1118632  -0.39891483]]

[[-0.38575752  0.00669319  0.01875155 -0.30840656 -0.42592098  0.03342828
  -0.04830691 -0.3478025  -0.66985192  0.03394474]]

[[-0.01145164 -0.47592759 -0.4677741  -0.14632405 -0.10280005 -0.45218439
  -0.38256378 -0.0107379   0.11186296 -0.39889374]]

[[-0.38576743  0.00670802  0.01875222 -0.30838834 -0.42591663  0.03342298
  -0.04830548 -0.3478159  -0.66985167

[[-0.01114847 -0.47638151 -0.46779413 -0.14688202 -0.10293343 -0.45202157
  -0.38260718 -0.0103279   0.11185486 -0.39825302]]

[[-0.38606827  0.00715784  0.01877203 -0.30783522 -0.42578418  0.03326209
  -0.04826271 -0.34822263 -0.6698434   0.03328857]]

[[-0.01113947 -0.47639496 -0.46779472 -0.14689858 -0.1029374  -0.45201674
  -0.38260846 -0.01031573  0.1118546  -0.39823399]]

[[-0.38607719  0.00717118  0.01877261 -0.30781881 -0.42578024  0.03325732
  -0.04826146 -0.34823471 -0.66984314  0.03326971]]

[[-0.01113051 -0.47640838 -0.4677953  -0.14691509 -0.10294135 -0.45201193
  -0.38260973 -0.0103036   0.11185434 -0.39821503]]

[[-0.38608609  0.00718447  0.01877318 -0.30780244 -0.42577631  0.03325257
  -0.0482602  -0.34824674 -0.66984287  0.0332509 ]]

[[-0.01112156 -0.47642175 -0.46779588 -0.14693155 -0.1029453  -0.45200713
  -0.382611   -0.01029151  0.11185408 -0.39819612]]

[[-0.38609497  0.00719773  0.01877376 -0.30778612 -0.42577239  0.03324782
  -0.04825896 -0.34825874 -0.66984261

[[-0.38638991  0.00763793  0.01879254 -0.30724357 -0.42564174  0.03309031
  -0.04821787 -0.34865769 -0.66983311  0.03260845]]

[[-0.01081635 -0.47687786 -0.46781538 -0.14749354 -0.10308041 -0.45184347
  -0.3826538  -0.00987856  0.11184447 -0.39755018]]

[[-0.38639792  0.00764988  0.01879304 -0.30722884 -0.42563818  0.03308603
  -0.04821676 -0.34866853 -0.66983284  0.0325915 ]]

[[-0.0108083  -0.47688988 -0.46781588 -0.14750836 -0.10308398 -0.45183916
  -0.38265491 -0.00986767  0.1118442  -0.39753314]]

[[-0.38640591  0.00766179  0.01879354 -0.30721414 -0.42563464  0.03308177
  -0.04821566 -0.34867934 -0.66983256  0.0325746 ]]

[[-0.01080027 -0.47690186 -0.46781638 -0.14752314 -0.10308754 -0.45183486
  -0.38265603 -0.00985681  0.11184393 -0.39751614]]

[[-0.38641388  0.00767367  0.01879404 -0.30719948 -0.4256311   0.03307752
  -0.04821457 -0.34869012 -0.66983229  0.03255774]]

[[-0.01079227 -0.47691381 -0.46781689 -0.14753788 -0.1030911  -0.45183057
  -0.38265714 -0.00984598  0.11184365

[[-0.38666545  0.0080485   0.01880956 -0.30673652 -0.42551904  0.03294335
  -0.04818018 -0.34903053 -0.6698231   0.03202509]]

[[-0.01053954 -0.47729083 -0.46783252 -0.14800342 -0.10320361 -0.45169526
  -0.38269189 -0.0095039   0.11183458 -0.39696365]]

[[-0.38667274  0.00805936  0.01881001 -0.30672309 -0.42551578  0.03293946
  -0.0481792  -0.34904041 -0.66982282  0.03200962]]

[[-0.01053221 -0.47730176 -0.46783297 -0.14801693 -0.10320688 -0.45169133
  -0.38269289 -0.00949398  0.1118343  -0.3969481 ]]

[[-0.38668003  0.0080702   0.01881045 -0.30670969 -0.42551253  0.03293557
  -0.04817821 -0.34905027 -0.66982254  0.0319942 ]]

[[-0.01052489 -0.47731266 -0.46783341 -0.1480304  -0.10321014 -0.45168742
  -0.38269389 -0.00948407  0.11183403 -0.39693259]]

[[-0.38668729  0.00808102  0.01881089 -0.30669632 -0.42550929  0.0329317
  -0.04817723 -0.3490601  -0.66982226  0.03197881]]

[[-0.0105176  -0.47732354 -0.46783386 -0.14804385 -0.1032134  -0.45168351
  -0.38269488 -0.0094742   0.11183375 

[[-0.38693087  0.00844339  0.01882549 -0.30624788 -0.42540025  0.03280194
  -0.04814452 -0.34938984 -0.66981242  0.03146246]]

[[-0.01027288 -0.47768803 -0.46784855 -0.14849479 -0.10332289 -0.45155266
  -0.38272795 -0.00914285  0.111824   -0.39639796]]

[[-0.38693754  0.00845331  0.01882588 -0.30623559 -0.42539726  0.03279839
  -0.04814363 -0.34939887 -0.66981214  0.03144831]]

[[-0.01026618 -0.477698   -0.46784895 -0.14850714 -0.10332589 -0.45154908
  -0.38272885 -0.00913377  0.11182372 -0.39638373]]

[[-0.3869442   0.00846321  0.01882627 -0.30622333 -0.42539427  0.03279485
  -0.04814274 -0.34940788 -0.66981185  0.03143418]]

[[-0.01025949 -0.47770796 -0.46784934 -0.14851947 -0.10332889 -0.4515455
  -0.38272974 -0.00912471  0.11182344 -0.39636954]]

[[-0.38695084  0.00847309  0.01882667 -0.3062111  -0.42539129  0.03279131
  -0.04814186 -0.34941688 -0.66981157  0.03142009]]

[[-0.01025282 -0.47771789 -0.46784974 -0.14853177 -0.10333189 -0.45154194
  -0.38273064 -0.00911567  0.11182316 

In [155]:
# true eigenvectors (to compare with approx eigenvectors from above)

from numpy import linalg as la
print(la.eig(X))
print()


(array([283.36779219 +0.j        ,  35.79672573 +0.j        ,
        -4.31914761+41.37611659j,  -4.31914761-41.37611659j,
         6.66846178+20.73720723j,   6.66846178-20.73720723j,
       -38.16903563 +0.j        ,  -6.28104106+11.93744717j,
        -6.28104106-11.93744717j, -20.1320285  +0.j        ]), array([[ 0.27487859+0.j        , -0.31835309+0.j        ,
         0.02224085-0.06399155j,  0.02224085+0.06399155j,
        -0.31617368+0.10448458j, -0.31617368-0.10448458j,
        -0.5216358 +0.j        ,  0.43423817-0.19687809j,
         0.43423817+0.19687809j,  0.22904293+0.j        ],
       [ 0.34040118+0.j        , -0.46666794+0.j        ,
        -0.08651583+0.41111595j, -0.08651583-0.41111595j,
        -0.27049879+0.13428873j, -0.27049879-0.13428873j,
         0.38196427+0.j        ,  0.21907683+0.02786987j,
         0.21907683-0.02786987j,  0.27847466+0.j        ],
       [ 0.31378265+0.j        , -0.48389634+0.j        ,
         0.04296298-0.13329933j,  0.04296298+0.13329

In [161]:
# selecting Column Vector
#print(X[:,:1])
print()

# transpose fnc
print(X.T)
#print(np.transpose(X))
print()
print()

# matrix multiplication
v1 = np.random.normal(5,1.5, size= (1, 10))
print(np.dot(v1, X))
print()
print(np.matmul(v1, X))
print()
print(v1 @ X)
print()

print(np.inner(v1, X))
print()


[[ 2 44 15 45 43 17 19 23 49 10]
 [38 32 44 31 27 40  3 42 43 16]
 [47 38 46 40 27  4 44  0 17  2]
 [12 36 19 10 25 46 25 30 13 45]
 [33 44  1 33 40 15 40 30 48  7]
 [43 16 43 17 42 26 37 19 48 40]
 [41 23 39 37 34 21 33 34 34 32]
 [14 27 17  8 28 39 41 11 31 38]
 [ 9 37 44 39 27 28 19 31 33 24]
 [ 4  1 10 30 49 38 15  1 38 20]]


[[1420.79626056 1818.2481429  1479.70654127 1494.74069489 1525.27359868
  1859.37314719 1836.75867725 1414.57502952 1642.79684212 1176.32082411]]

[[1420.79626056 1818.2481429  1479.70654127 1494.74069489 1525.27359868
  1859.37314719 1836.75867725 1414.57502952 1642.79684212 1176.32082411]]

[[1420.79626056 1818.2481429  1479.70654127 1494.74069489 1525.27359868
  1859.37314719 1836.75867725 1414.57502952 1642.79684212 1176.32082411]]

[[1452.27598921 1674.64760992 1564.79424416 1610.55411393 1940.19480905
  1465.55169759 1641.23240269 1168.80589939 1993.37317632 1291.47075737]]



In [75]:
# eigenvalues, eigenvectors, norm fncs

# 1st array = eigenvalues in asceding order
# 2nd array = normalized eigenvectors corresponding to eigenvalue
from numpy import linalg as la
print(la.eig(X))
print()
print(la.norm(X))


(array([ 5.05700300e+03 +0.j        , -7.55596332e+01+78.92195506j,
       -7.55596332e+01-78.92195506j,  9.72631616e+01+45.88863327j,
        9.72631616e+01-45.88863327j, -3.07272075e+01+92.7453888j ,
       -3.07272075e+01-92.7453888j , -1.28237390e+00+95.88986704j,
       -1.28237390e+00-95.88986704j,  7.96321580e+01+53.21038417j,
        7.96321580e+01-53.21038417j,  1.84561237e+01+91.51333679j,
        1.84561237e+01-91.51333679j,  9.15573499e+01 +9.93343771j,
        9.15573499e+01 -9.93343771j, -9.38530775e+01 +6.16764913j,
       -9.38530775e+01 -6.16764913j,  6.84042720e+01+60.28344932j,
        6.84042720e+01-60.28344932j, -8.11135272e+01+37.00605669j,
       -8.11135272e+01-37.00605669j, -5.27928769e+01+71.40138549j,
       -5.27928769e+01-71.40138549j,  2.52209351e+01+82.77426879j,
        2.52209351e+01-82.77426879j,  5.06881431e+01+70.70982816j,
        5.06881431e+01-70.70982816j, -8.27241607e+01 +0.j        ,
        7.89900357e+01 +0.j        , -6.31856193e+01+50.17002

# 
### 2. Deflation Method

### 3. Eigengame with Parallelism

### 4. Deflation with Parallelism